"""add new tables

Revision ID: 4e0f87e93b7a
Revises: 4df671d34113
Create Date: 2026-07-15 16:18:12.513001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0f87e93b7a'
down_revision: Union[str, Sequence[str], None] = '4df671d34113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_queries',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source', 'query', 'page')
    )
    op.create_table('scrape_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('impersonate_profile', sa.String(length=50), nullable=True),
    sa.Column('proxy', sa.String(length=255), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('was_blocked', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('raw_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'raw_html')
    op.drop_table('scrape_requests')
    op.drop_table('listing_queries')
    # ### end Alembic commands ###
